interface User {
  avatar?: string,
  beDeleted?: boolean,
  birthday?: string,
  email?: string,
  gender?: number,
  gmtCreate?: string,
  gmtModified?: string,
  id?: number,
  nickname?: string,
  password?: string,
  roleId?: number,
  signature?: string,
  username?: string,
  point?: number,
}